version: "2"
services:
  app:
    build: ./app
    container_name: "Flask_App4"
    links:
      - db
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app


  db:
    image: mysql:5.7
    container_name: "MySQL_Database4"
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro

volumes:
  app: